"""empty message

Revision ID: 25554b9f9905
Revises: 1ec3bbb378f6
Create Date: 2019-10-06 15:39:23.671511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25554b9f9905'
down_revision = '1ec3bbb378f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_completed', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_completed')
    # ### end Alembic commands ###
